// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BGLAppInfo;

@interface BGLAppInfo : NSObject
+ (instancetype)makeWithIsProductionEnv:(nullable NSNumber *)isProductionEnv
    jPushId:(nullable NSString *)jPushId
    projectName:(nullable NSString *)projectName;
@property(nonatomic, strong, nullable) NSNumber * isProductionEnv;
@property(nonatomic, copy, nullable) NSString * jPushId;
@property(nonatomic, copy, nullable) NSString * projectName;
@end

/// The codec used by BGLFlutterCallNativeApi.
NSObject<FlutterMessageCodec> *BGLFlutterCallNativeApiGetCodec(void);

@protocol BGLFlutterCallNativeApi
/// @return `nil` only when `error != nil`.
- (nullable BGLAppInfo *)getAppInfoWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)sensorAddTrackEventName:(NSString *)eventName paramsMap:(NSDictionary<NSString *, id> *)paramsMap completion:(void (^)(FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)sensorGetPresetPropertyPropertyName:(NSString *)propertyName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)getTestWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpBGLFlutterCallNativeApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BGLFlutterCallNativeApi> *_Nullable api);

extern void SetUpBGLFlutterCallNativeApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BGLFlutterCallNativeApi> *_Nullable api, NSString *messageChannelSuffix);

/// The codec used by BGLNativeCallFlutterApi.
NSObject<FlutterMessageCodec> *BGLNativeCallFlutterApiGetCodec(void);

@interface BGLNativeCallFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)getBagelTokenWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)getSopListWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
