// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "BGLMessages.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface BGLAppInfo ()
+ (BGLAppInfo *)fromList:(NSArray *)list;
+ (nullable BGLAppInfo *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation BGLAppInfo
+ (instancetype)makeWithIsProductionEnv:(nullable NSNumber *)isProductionEnv
    jPushId:(nullable NSString *)jPushId
    projectName:(nullable NSString *)projectName {
  BGLAppInfo* pigeonResult = [[BGLAppInfo alloc] init];
  pigeonResult.isProductionEnv = isProductionEnv;
  pigeonResult.jPushId = jPushId;
  pigeonResult.projectName = projectName;
  return pigeonResult;
}
+ (BGLAppInfo *)fromList:(NSArray *)list {
  BGLAppInfo *pigeonResult = [[BGLAppInfo alloc] init];
  pigeonResult.isProductionEnv = GetNullableObjectAtIndex(list, 0);
  pigeonResult.jPushId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.projectName = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable BGLAppInfo *)nullableFromList:(NSArray *)list {
  return (list) ? [BGLAppInfo fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.isProductionEnv ?: [NSNull null],
    self.jPushId ?: [NSNull null],
    self.projectName ?: [NSNull null],
  ];
}
@end

@interface BGLFlutterCallNativeApiCodecReader : FlutterStandardReader
@end
@implementation BGLFlutterCallNativeApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [BGLAppInfo fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface BGLFlutterCallNativeApiCodecWriter : FlutterStandardWriter
@end
@implementation BGLFlutterCallNativeApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BGLAppInfo class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface BGLFlutterCallNativeApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation BGLFlutterCallNativeApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[BGLFlutterCallNativeApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[BGLFlutterCallNativeApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *BGLFlutterCallNativeApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    BGLFlutterCallNativeApiCodecReaderWriter *readerWriter = [[BGLFlutterCallNativeApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpBGLFlutterCallNativeApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BGLFlutterCallNativeApi> *api) {
  SetUpBGLFlutterCallNativeApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpBGLFlutterCallNativeApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BGLFlutterCallNativeApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.getAppInfo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:BGLFlutterCallNativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAppInfoWithError:)], @"BGLFlutterCallNativeApi api (%@) doesn't respond to @selector(getAppInfoWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        BGLAppInfo *output = [api getAppInfoWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorAddTrack", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:BGLFlutterCallNativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sensorAddTrackEventName:paramsMap:completion:)], @"BGLFlutterCallNativeApi api (%@) doesn't respond to @selector(sensorAddTrackEventName:paramsMap:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        NSDictionary<NSString *, id> *arg_paramsMap = GetNullableObjectAtIndex(args, 1);
        [api sensorAddTrackEventName:arg_eventName paramsMap:arg_paramsMap completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorGetPresetProperty", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:BGLFlutterCallNativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sensorGetPresetPropertyPropertyName:error:)], @"BGLFlutterCallNativeApi api (%@) doesn't respond to @selector(sensorGetPresetPropertyPropertyName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_propertyName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api sensorGetPresetPropertyPropertyName:arg_propertyName error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.getTest", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:BGLFlutterCallNativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getTestWithCompletion:)], @"BGLFlutterCallNativeApi api (%@) doesn't respond to @selector(getTestWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getTestWithCompletion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *BGLNativeCallFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

@interface BGLNativeCallFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation BGLNativeCallFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)getBagelTokenWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getBagelToken", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:BGLNativeCallFlutterApiGetCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSString *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)getSopListWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getSopList", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:BGLNativeCallFlutterApiGetCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSString *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
@end

