// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AppInfo {
    private @Nullable Boolean isProductionEnv;

    public @Nullable Boolean getIsProductionEnv() {
      return isProductionEnv;
    }

    public void setIsProductionEnv(@Nullable Boolean setterArg) {
      this.isProductionEnv = setterArg;
    }

    private @Nullable String jPushId;

    public @Nullable String getJPushId() {
      return jPushId;
    }

    public void setJPushId(@Nullable String setterArg) {
      this.jPushId = setterArg;
    }

    private @Nullable String projectName;

    public @Nullable String getProjectName() {
      return projectName;
    }

    public void setProjectName(@Nullable String setterArg) {
      this.projectName = setterArg;
    }

    public static final class Builder {

      private @Nullable Boolean isProductionEnv;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsProductionEnv(@Nullable Boolean setterArg) {
        this.isProductionEnv = setterArg;
        return this;
      }

      private @Nullable String jPushId;

      @CanIgnoreReturnValue
      public @NonNull Builder setJPushId(@Nullable String setterArg) {
        this.jPushId = setterArg;
        return this;
      }

      private @Nullable String projectName;

      @CanIgnoreReturnValue
      public @NonNull Builder setProjectName(@Nullable String setterArg) {
        this.projectName = setterArg;
        return this;
      }

      public @NonNull AppInfo build() {
        AppInfo pigeonReturn = new AppInfo();
        pigeonReturn.setIsProductionEnv(isProductionEnv);
        pigeonReturn.setJPushId(jPushId);
        pigeonReturn.setProjectName(projectName);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(isProductionEnv);
      toListResult.add(jPushId);
      toListResult.add(projectName);
      return toListResult;
    }

    static @NonNull AppInfo fromList(@NonNull ArrayList<Object> __pigeon_list) {
      AppInfo pigeonResult = new AppInfo();
      Object isProductionEnv = __pigeon_list.get(0);
      pigeonResult.setIsProductionEnv((Boolean) isProductionEnv);
      Object jPushId = __pigeon_list.get(1);
      pigeonResult.setJPushId((String) jPushId);
      Object projectName = __pigeon_list.get(2);
      pigeonResult.setProjectName((String) projectName);
      return pigeonResult;
    }
  }

  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }

  private static class FlutterCallNativeApiCodec extends StandardMessageCodec {
    public static final FlutterCallNativeApiCodec INSTANCE = new FlutterCallNativeApiCodec();

    private FlutterCallNativeApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return AppInfo.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof AppInfo) {
        stream.write(128);
        writeValue(stream, ((AppInfo) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface FlutterCallNativeApi {

    @NonNull 
    AppInfo getAppInfo();

    void sensorAddTrack(@NonNull String eventName, @NonNull Map<String, Object> paramsMap, @NonNull VoidResult result);

    @NonNull 
    String sensorGetPresetProperty(@NonNull String propertyName);

    /** The codec used by FlutterCallNativeApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return FlutterCallNativeApiCodec.INSTANCE;
    }
    /**Sets up an instance of `FlutterCallNativeApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable FlutterCallNativeApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable FlutterCallNativeApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.getAppInfo" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  AppInfo output = api.getAppInfo();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorAddTrack" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String eventNameArg = (String) args.get(0);
                Map<String, Object> paramsMapArg = (Map<String, Object>) args.get(1);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.sensorAddTrack(eventNameArg, paramsMapArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorGetPresetProperty" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String propertyNameArg = (String) args.get(0);
                try {
                  String output = api.sensorGetPresetProperty(propertyNameArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class NativeCallFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public NativeCallFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public NativeCallFlutterApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /** Public interface for sending reply. */ 
    /** The codec used by NativeCallFlutterApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return new StandardMessageCodec();
    }
    public void getBagelToken(@NonNull NullableResult<String> result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getBagelToken" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          null,
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), (String) listReply.get(2)));
              } else {
                @SuppressWarnings("ConstantConditions")
                String output = (String) listReply.get(0);
                result.success(output);
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void getSopList(@NonNull Result<String> result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getSopList" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          null,
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), (String) listReply.get(2)));
              } else if (listReply.get(0) == null) {
                result.error(new FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""));
              } else {
                @SuppressWarnings("ConstantConditions")
                String output = (String) listReply.get(0);
                result.success(output);
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
