// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppInfo {
  var isProductionEnv: Bool? = nil
  var jPushId: String? = nil
  var projectName: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> AppInfo? {
    let isProductionEnv: Bool? = nilOrValue(__pigeon_list[0])
    let jPushId: String? = nilOrValue(__pigeon_list[1])
    let projectName: String? = nilOrValue(__pigeon_list[2])

    return AppInfo(
      isProductionEnv: isProductionEnv,
      jPushId: jPushId,
      projectName: projectName
    )
  }
  func toList() -> [Any?] {
    return [
      isProductionEnv,
      jPushId,
      projectName,
    ]
  }
}

private class FlutterCallNativeApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return AppInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterCallNativeApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppInfo {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterCallNativeApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterCallNativeApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterCallNativeApiCodecWriter(data: data)
  }
}

class FlutterCallNativeApiCodec: FlutterStandardMessageCodec {
  static let shared = FlutterCallNativeApiCodec(readerWriter: FlutterCallNativeApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterCallNativeApi {
  func getAppInfo() throws -> AppInfo
  func sensorAddTrack(eventName: String, paramsMap: [String: Any], completion: @escaping (Result<Void, Error>) -> Void)
  func sensorGetPresetProperty(propertyName: String) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterCallNativeApiSetup {
  /// The codec used by FlutterCallNativeApi.
  static var codec: FlutterStandardMessageCodec { FlutterCallNativeApiCodec.shared }
  /// Sets up an instance of `FlutterCallNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterCallNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAppInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.getAppInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppInfoChannel.setMessageHandler(nil)
    }
    let sensorAddTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorAddTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sensorAddTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventNameArg = args[0] as! String
        let paramsMapArg = args[1] as! [String: Any]
        api.sensorAddTrack(eventName: eventNameArg, paramsMap: paramsMapArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sensorAddTrackChannel.setMessageHandler(nil)
    }
    let sensorGetPresetPropertyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_example_package.FlutterCallNativeApi.sensorGetPresetProperty\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sensorGetPresetPropertyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let propertyNameArg = args[0] as! String
        do {
          let result = try api.sensorGetPresetProperty(propertyName: propertyNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sensorGetPresetPropertyChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeCallFlutterApiProtocol {
  func getBagelToken(completion: @escaping (Result<String?, FlutterError>) -> Void)
  func getSopList(completion: @escaping (Result<String, FlutterError>) -> Void)
}
class NativeCallFlutterApi: NativeCallFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  func getBagelToken(completion: @escaping (Result<String?, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getBagelToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
  func getSopList(completion: @escaping (Result<String, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pigeon_example_package.NativeCallFlutterApi.getSopList\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}
